# Display a box
print("Please enter a character for Beep's eyes")
eye = input()
print("       ##########")
print("       #  {0}  {1}  #".format(eye,eye))
print("       #  ----  #")
print("       ##########")
print("          ####")
print("    ################")
print("   ## ############ ##")
print("  ##  ############  ##")
print(" ##   ############   ##")
print("      ############")
print("      ###      ###")
print("      ###      ###")
print("      ###      ###")
print("      ###      ###")
